put_metadata <- function(metadata,
                         destination,
                         verbose = FALSE) {

  put_path <- fix_path("metadata.csv", destination, verbose = verbose)

  make_prefix(destination)

  schema_check <- all(c("schema_ver", "base_path", "diffed", "backup_count") %in% names(unlist(metadata)))

  if(!(schema_check)) {
    stop("metadata schema check failed. Please pas a valid metadata list, as generated by generate_metadata()")
  }

  metadata_string <- map(metadata, paste, collapse = "|")
  metadata_df <- as.data.frame(metadata_string)
  write_csv_arrow(metadata_df, put_path, include_header = TRUE)
  return(TRUE)
}


